import "./globals.css";
import NavBar from "./components/sub-comp/NavBar";
import ParticlesComponent from "./components/particles/Particles";
import { particlesConfig } from "./utils/particles.config";
import ParticlesGB from "./components/particles/ParticlesGB";
import SideCard from "./components/sub-comp/SideCard";
import Progress from "./components/sub-comp/progressbar";
import Script from "next/script";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" crossOrigin="true" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400..900&family=Courgette&family=Josefin+Sans:ital,wght@0,100..700;1,100..700&family=Satisfy&display=swap" rel="stylesheet" />
        <Script src="http://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></Script>
      </head>
      <body className={`antialiased`}>
        <div className="absolute w-full h-full z-0 flex justify-center items-center">
          <img className="absolute bg-blend-difference invert opacity-15 scale-95" src="https://particles.js.org/images/smalldeer.svg" alt="svg" />
        </div>

        <Progress />
        <ParticlesComponent options={particlesConfig} />
        <ParticlesGB />
        <SideCard />
        {children}
        <NavBar />
      </body>
    </html>
  );
}
